In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Output: [5 7 9]


[5 7 9]


In [ ]:
import numpy as np 

array = np.array([[['A','B','C'],
                  ['D','E','F'],
                  ['G','H','I']]]) # 2D array Raw Column

In [2]:
import numpy as np 

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])
print(array.ndim)

3


In [ ]:
import numpy as np 

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])
print(array.shape) # Tuple of integers   Raw,Column

(3, 3, 3)


In [ ]:
import numpy as np 

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']]])
print(array.shape) # Still 3 dimensional

(2, 3, 3)


In [14]:
import numpy as np 

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],#0
                  [['J','K','L'],['M','N','O'],['P','Q','R']],#1
                  [['S','T','U'],['V','W','X'],['Y','Z','']]]) #2

print(array[0,0,1])
print(array[0,1,0])
print(array[1,1,1])  

B
D
N


In [16]:
import numpy as np 

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])
word = array[0,0,0] + array[2,0,0] + array[2,0,0]
print(word)

ASS


## Slicing using numpy

In [26]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0])
print(array[-2])
print(array[0:3])
print(array[::2])
print(array[::-2])

print(array[:,0])

print(array[:,0:3])

print(array[:, :1:4])

print(array[:,::2])

print(array[0:2 , 0:2])

print(array[0:2, 2:])

print(array[2:, 0:2])

print(array[2:, 2:])
                 
## array[start:end:step]
               

[1 2 3 4]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


## Arithmatic

In [28]:
# Scaler arithmatic

array = np.array([1,2,3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
# Vectorized math func

array = np.array([1.01,2.5,3.99])

print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)




[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [32]:
# Exercise

radii =np.array([1,2,3])

print(np.pi *radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [33]:
# Element wise arithmatic

array1 = np.array([1 , 2 , 3])
array2 = np.array([4 , 5 , 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [37]:
# Comparison Operators

scores = np.array([91,55,100,73,82,64])

print(scores == 100)
print(scores >= 60)
print(scores<60)

scores[scores<60] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]


# Brodcasting

In [40]:
import numpy as np

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)

print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [44]:
import numpy as np

array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)

print(array2.shape)
print(array1*array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [45]:
import numpy as np

array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])
array2 = np.array([[1,2], [2,3], [3,4], [4,5]])

print(array1.shape)

print(array2.shape)
print(array1*array2)

(4, 4)
(4, 2)


ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

In [47]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 =np.array([[1] , [2] , [3] , [4] , [5] , [6] , [7] , [8] , [9] ,[10]])

print(array1.shape)
print(array2.shape)

print(array1* array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Aggregate Function = summarize data and typically return a single value

In [58]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print (np.sum(array))
print (np.mean(array))
print (np.std(array))
print (np.var(array))
print (np.min(array))
print (np.max(array))
print (np.argmin(array))
print (np.argmax(array))

print(np.sum(array, axis=0))
print(np.sum(array, axis=1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


## Filtering = Refers to the process of selecting elements from an array that match a given condition

In [66]:
import numpy as np  
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])
teenagers = ages[ages < 18]
adults = ages[ages >= 18]
adults = ages[(ages  >=18) & (ages < 65)]
adults = ages[(ages  < 18) | (ages >= 65)]
seniors = ages[ages >=65]
evens = ages[ages % 2 ==0]
odds = ages[ages % 2 != 0]


print(teenagers) # Boolean indexing
print(ages)
print(adults)
print(seniors)
print(evens) 
print(odds)

[17 16 15]
[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]
[17 16 65 15 99]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [67]:
import numpy as np  
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

adults = np.where(ages >= 18,ages, 0)

print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


## Random Numbers

In [71]:
import numpy as np  

rng = np.random.default_rng()

print(rng.integers(1,7))
print(rng.integers(low=1,high=101,size=3))
print(rng.integers(low=1,high=101,size=(3,2)))

5
[50 34 82]
[[55 77]
 [51 91]
 [61 11]]


In [72]:
import numpy as np  

rng = np.random.default_rng(seed=1)


print(rng.integers(low=1,high=101,size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [74]:
import numpy as np  

print(np.random.uniform())

print(np.random.uniform(low=-1,high=1,size=3))

0.7047339893913558
[-0.14066054  0.46413988  0.9609231 ]


In [76]:

rng = np.random.default_rng()
array= np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)


[2 4 3 5 1]


In [77]:
rng = np.random.default_rng()

fruits = np.array(["apple","orange","coconut","pinapple"])

print(fruits)

['apple' 'orange' 'coconut' 'pinapple']


In [80]:
rng = np.random.default_rng()

fruits = np.array(["apple","orange","coconut","pinapple"])
fruits=rng.choice(fruits)
print(fruits)

pinapple


In [82]:
rng = np.random.default_rng()

fruits = np.array(["apple","orange","coconut","pinapple"])
fruits=rng.choice(fruits, size=3)
print(fruits)

['coconut' 'pinapple' 'orange']


In [83]:
rng = np.random.default_rng()

fruits = np.array(["apple","orange","coconut","pinapple"])
fruits=rng.choice(fruits, size=(3,3))
print(fruits)

[['coconut' 'coconut' 'pinapple']
 ['coconut' 'orange' 'coconut']
 ['apple' 'pinapple' 'pinapple']]
