NumPy = Numerical Python
It helps you work with large amounts of data easily and super fast.


In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Output: [5 7 9]


[5 7 9]


In [11]:
import = np.array([['A]])

SyntaxError: unterminated string literal (detected at line 1) (3410262183.py, line 1)

## Creating ndarray from scratch in Phitron

In [ ]:
import numpy as np

arr = np.zeros((1,3))
print(arr)  #new raw colum added
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


arr = np.zeros_like

[[0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2
3


In [ ]:
arr = np.full((4,3),10)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12


In [ ]:
arr = np.full((4,3),True)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
bool
(4, 3)
2
12


## Arrar creation with random value

In [ ]:
# np.random.rand(shaape)

arr = np.random.rand(2,3) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

# If i run always it will change number

[[0.88748828 0.63318736 0.55901349]
 [0.34552877 0.03876834 0.77442306]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [ ]:
# np.random.randint(shaape)

arr = np.random.randint(1,10 , (2,3)) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[7 2 2]
 [3 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [ ]:
# np.random.randint(shaape)

arr = np.random.randint(1,10 , (2,)) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[8 3]
<class 'numpy.ndarray'>
int32
(2,)
1
2


In [ ]:
# np.random.randint(starting,end,shape)

arr = np.random.randint(1,10 , (10,10)) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[4 1 3 2 1 2 3 1 1 7]
 [9 7 1 6 1 3 2 7 9 7]
 [2 8 6 1 5 6 5 2 8 2]
 [4 7 6 2 3 3 8 5 8 8]
 [9 4 7 3 7 9 1 2 4 6]
 [6 9 1 7 8 5 8 4 4 7]
 [1 2 2 7 2 5 4 9 1 2]
 [5 7 5 1 5 7 1 6 9 1]
 [8 7 2 7 1 5 8 6 5 3]
 [7 2 1 4 6 6 4 3 1 5]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


In [ ]:
# np.random.uniform(shaape)----Float

arr = np.random.uniform(50,100 , (3,4)) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[52.40617565 92.46832978 51.11044167 90.1770389 ]
 [76.18517381 86.84799148 52.23919452 71.58713123]
 [99.17408001 75.80088374 56.51317443 70.34079686]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


In [ ]:
# np.random.uniform(shaape)----Float

arr = np.random.uniform(50,100 , (3,3,4)) # 0 to random value gives me in a logical way

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[81.18923829 60.02468402 92.66501566 61.6454914 ]
  [93.71714842 89.05075315 74.92235688 73.50740412]
  [96.92574565 68.18897625 97.33811969 80.09746629]]

 [[52.34549365 59.52901868 99.44969953 56.97019334]
  [97.88955457 68.33937625 97.1313368  58.53552091]
  [92.73017471 80.2047031  69.79057874 87.33545213]]

 [[96.31158006 52.55118459 95.02711621 79.21263693]
  [70.30258095 91.43190858 85.86425905 71.9320348 ]
  [70.9783182  93.06224867 94.54219936 97.23311833]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## ndarray creation from range

In [ ]:
# np.arrange(first,end,step) --> similar to range function

arr = np.arange(1,10,1)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
# np.arrange(first,end,step) --> similar to range function

arr = np.arange(1,10,2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
1
5


In [ ]:
arr = np.arange(1,10,1).reshape(3,3)


print(arr)

print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [ ]:
arr = np.arange(1,10,1)
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
# np.linear space (start,end,koita)

arr= np.linspace(1,10,11)

print(arr)

print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [ ]:
# np.linear space (start,end,koita)

arr= np.linspace(1,10,15)

print(arr)

print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1
15


In [ ]:
# np.longspace(start , end(included), koita)


import numpy as np

arr = np.logspace(1, 4, 5)

print(arr)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


In [ ]:
arr = np.logspace(0, 4, 5)

print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [ ]:
arr = np.logspace(0, 4, 6)

print(arr)

[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]


In [ ]:
arr = np.logspace(0, 4, 6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## Diagonal and Identity matrix------1>Primary....2>Secondary

Creating matrix for Linear Algebra

In [ ]:
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [ ]:
# Identity Matrix

identity_mat = np.eye(3)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [ ]:
# Identity Matrix

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [ ]:
# Identity Matrix

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)


# np.eye(row,column)

mat = np.eye(3,4)

print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# Identity Matrix

identity_mat = np.eye(4)



# np.eye(row,column,k)

mat = np.eye(3,4,-1)

print(mat)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# Identity Matrix

identity_mat = np.eye(4)



# np.eye(row,column,k)

mat = np.eye(3,4,1)

print(mat)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## ndarray indexing and slicing

In [ ]:
# Indexing

arr1 = [1,2,3,4,5]
arr2 = [1,2,3]

print(arr1)
print(arr2)

[1, 2, 3, 4, 5]
[1, 2, 3]


In [ ]:

print(arr1[2])


arr1[2] = 100
print(arr1)

3
[1, 2, 100, 4, 5]


In [ ]:
print(arr2)

[1, 2, 3]


In [ ]:
print(arr2[0][1])

TypeError: 'int' object is not subscriptable

In [ ]:
# Indexing
arr1 = [1,2,3,4,5]
arr2 = [1,2,3]
print(arr1)
print(arr2)

[1, 2, 3, 4, 5]
[1, 2, 3]


In [ ]:
print(arr1[2])

3


In [ ]:
arr1[2] = 100
print(arr1)

[1, 2, 100, 4, 5]


In [ ]:
print(arr1)

[1, 2, 100, 4, 5]


In [ ]:
import numpy as np
arr2 = [[1,2,3],[4,5,6]]
arr2 =np.array(arr2)
print(arr2)

print(arr2[0][1]) # 0 number row and 1 number column
print(arr2[0][2])

[[1 2 3]
 [4 5 6]]
2
3


In [ ]:
arr2[0][2] = 100
print(arr2)

[[  1   2 100]
 [  4   5   6]]


## Slicing   ;1d = arr[start:end:step]

In [ ]:
print(arr1)
arr1=[1,2,100,4,5]
print(arr1)

[[1, 2, 3], [4, 5, 6]]
[1, 2, 100, 4, 5]


In [ ]:
arr1_mod = arr1[1:4]

print(arr1_mod)

[2, 100, 4]


## 2d Slicing 
arr[row_start : row_end : step : column_start : column_end :step]

In [ ]:
#print(arr2)

row_0 =arr2[0:1 ,]

print(row_0)

[[  1   2 100]]


In [ ]:
row_0 =arr2[0:1 ,]
row_1 = arr2[1:, ]

print(row_0)
print(row_1)


# Getting a column

col_0 = arr2[:: , 0:1]
print(col_0)

[[  1   2 100]]
[[4 5 6]]
[[1]
 [4]]


In [ ]:
row_0 =arr2[0:1 ,]
row_1 = arr2[1:, ]



# Getting a column

col_0 = arr2[:: , 0:1]
col_1 =arr2[::,1:2]

print(col_0)
print(col_1)


# Getting a portion

portion =arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


## Ndarray copy Advanced Indexing and Iteration

In [12]:
arr1_mod = arr1[1:4]
arr1_mod[0] = 100

print(arr1)
print(arr1_mod)


NameError: name 'arr1' is not defined

In [ ]:
import numpy as np

# Create the original array
arr1 = np.array([1, 2, 3, 4 , 5])

# Create a view (slice) of arr1
arr1_mod = arr1[1:4]

# Modify the first element of arr1_mod
arr1_mod[0] = 100

# Print both arrays
print(arr1)      # Will print: [  1 100   3   4]
print(arr1_mod)  # Will print: [100   3   4]

[  1 100   3   4   5]
[100   3   4]


In [ ]:

arr1_mod = arr1[1:4].copy()


print(arr1)      
print(arr1_mod)  

[  1 100   3   4   5]
[100   3   4]


In [22]:
arr1_mod = arr1[1:4].copy()

arr1[1] = 2
  
arr1_mod[2]= 200  
  
print(arr1_mod[2]) 

print(arr1) 

200
[1 2 3 4 5]


## Advanced Indexing

In [ ]:
lst =np.array([10,20,30,40])

values = lst[[2,3]]

print(values)

[30 40]


In [31]:
arr2 = [[1,2,3],[4,5,6]]
arr2 =np.array(arr2)
print(arr2)

print(arr2[[0,1] , [1,2]])

# Boolean
print(arr2[arr2>2])



[[1 2 3]
 [4 5 6]]
[2 6]
[3 4 5 6]


In [32]:
arr2[arr2>2] = 0
print(arr2)

[[1 2 0]
 [0 0 0]]


## Iteration

In [35]:
arr = np.array([ [10,20,30] , [100,200,300] ])
print(arr)

for i in arr:
    print(i)

[[ 10  20  30]
 [100 200 300]]
[10 20 30]
[100 200 300]


In [36]:
for i in arr:
    for j in i :
        print(j)

10
20
30
100
200
300


In [37]:
for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300


In [38]:
arr = np.array([1,2,3])
print(arr.ndim)

1


In [39]:
arr = np.array([1,2,3,2.5])
print(arr.dtype)

float64


In [41]:
arr = np.full((2,2),np.inf)
print(arr)

[[inf inf]
 [inf inf]]


In [42]:
arr = np.array([[10,20,30],[40,50,60]])

print(arr[:,1])

[20 50]


In [43]:
arr = np.array([1,2,3,4,5])
arr[1:4]= 0
print(arr)

[1 0 0 0 5]


## Practice Problem

## 1. You have a list of temperatures recorded in Celsius. Your task is to:
Create a NumPy array from the given list.
Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
Print the new Fahrenheit array.



In [46]:
temperatures = [23.5, 24.0, 22.8, 25.1, 26.3, 24.7, 23.9, 22.4, 21.8, 24.5]
arr =np.array(temperatures)
print(arr)

[23.5 24.  22.8 25.1 26.3 24.7 23.9 22.4 21.8 24.5]


In [49]:
import numpy as np
temperatures_C = [23.5, 24.0, 22.8, 25.1, 26.3, 24.7, 23.9, 22.4, 21.8, 24.5]
celcius =np.array(temperatures_C)

farhenhite = celcius*1.8+32
print(farhenhite)

[74.3  75.2  73.04 77.18 79.34 76.46 75.02 72.32 71.24 76.1 ]


## 2.  You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes.


In [51]:
import numpy as np
lap_times = [62.5, 61.8, 63.2, 60.9, 62.1, 61.4]

lap_times_array = np.array(lap_times)
print(lap_times_array)
print(type(lap_times_array))
print(lap_times_array.dtype)
print(lap_times_array.shape)
print(lap_times_array.ndim)
print(lap_times_array.size)

[62.5 61.8 63.2 60.9 62.1 61.4]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [52]:
import numpy as np
lap_times = [62.5, 61.8, 63.2, 60.9, 62.1, 61.4]

lap_times_array = np.array(lap_times)

lap_times_minutes =lap_times_array/60
print(lap_times_minutes)

[1.04166667 1.03       1.05333333 1.015      1.035      1.02333333]
